variables: 
    IMAGE_NAME: christophedelapierre/briefdevo
    IMAGE_TAG:  latest
    # MONGODB_URI: mongodb+srv://christophedelapierresimplon:DFf0uvbc1bqGUwMj@clustersimplonchristoph.btp4k2s.mongodb.net/
    MONGODB_URI: $MONGODB_URI

started:
    image: node:16-alpine
    before_script:
        - apt-get update && apt-get install nodejs
        - npm install
    script:
        - npm run start


build_image:
    image: docker:20.10.16
    services:
        - docker:20.10.16-dind
        - mongo
    variables:
        DOCKER_TLS_CERTDIR: "/certs"
    before_script:
        -  docker login -u $REGISTRY_USER -p $REGISTRY_PASS
    script:
        # -  docker build  -t $IMAGE_NAME:$IMAGE_TAG .
        -  docker build -t christophedelapierre/briefdevo:latest . 
        -  docker push $IMAGE_NAME:$IMAGE_TAG

